services:
  portfolio:
    image: node:20-alpine
    user: node:node
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "80:3000"
    command: sh -c "npm install --loglevel info && npm start"
